# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  ocelot6:
    image: ${IMAGE_DOTNET_V6}
    container_name: dotnet-ocelot6-srv_${PROJECT_NAME}
    ports:
      - "5000:5000"
    volumes:
      - ${DOTNET_OCELOT_APP_PATH}:/app
      - ${DOTNET_OCELOT_PUBLISH_PATH}:/app/publish
    networks:
      - service_network
  ocelot3:
    image: ${IMAGE_DOTNET_V3}
    container_name: dotnet-ocelot3-srv_${PROJECT_NAME}
    ports:
      - "5050:5000"
    volumes:
      - ${DOTNET_OCELOT3_APP_PATH}:/app
      - ${DOTNET_OCELOT3_PUBLISH_PATH}:/app/publish
    networks:
      - service_network
  auth:
    image: ${IMAGE_DOTNET_V6}
    container_name: dotnet-auth-srv_${PROJECT_NAME}
    ports:
      - "5001:5000"
    volumes:
      - ${DOTNET_AUTH_APP_PATH}:/app
      - ${DOTNET_AUTH_PUBLISH_PATH}:/app/publish
    networks:
      - service_network
  core:
    image: ${IMAGE_DOTNET_V6}
    container_name: dotnet-core-srv_${PROJECT_NAME}
    ports:
      - "5002:5000"
    volumes:
      - ${DOTNET_CORE_APP_PATH}:/app
      - ${DOTNET_CORE_PUBLISH_PATH}:/app/publish
    networks:
      - service_network
  utils:
    image: ${IMAGE_DOTNET_V3}
    container_name: dotnet-utils-srv_${PROJECT_NAME}
    ports:
      - "5003:5000"
    volumes:
      - ${DOTNET_UTILS_APP_PATH}:/app
      - ${DOTNET_UTILS_PUBLISH_PATH}:/app/publish
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
